# Generated by Django 2.2 on 2023-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=250)),
                ('cnf_pwd', models.CharField(max_length=250)),
            ],
        ),
    ]
