# Generated by Django 2.2 on 2023-04-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='i_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='v_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
