# Generated by Django 2.2 on 2023-04-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20230407_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_type', models.CharField(blank=True, max_length=250, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=250, null=True)),
                ('v_type', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
