# Generated by Django 2.2 on 2023-04-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
