# Generated by Django 2.2 on 2023-04-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_min'),
    ]

    operations = [
        migrations.DeleteModel(
            name='min',
        ),
    ]
