# Generated by Django 4.1.13 on 2024-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='threshold',
            field=models.IntegerField(default=10),
        ),
    ]
