# Generated by Django 4.1.13 on 2024-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_item_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='items_sold',
            field=models.IntegerField(default=0),
        ),
    ]
