# Generated by Django 4.1.13 on 2024-04-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_rename_date_sale__date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='_date',
            new_name='sale_date',
        ),
    ]
