# Generated by Django 4.1.13 on 2024-04-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_sale_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_cost',
            new_name='totalcost',
        ),
    ]
