# Generated by Django 4.1.13 on 2024-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_total_cost_sale_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
