# Generated by Django 4.1.13 on 2024-04-14 16:26

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='my_id',
            field=models.CharField(default=project.models.id_generator, max_length=6, unique=True),
        ),
    ]
