# Generated by Django 4.1.13 on 2024-04-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_item_my_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='my_id',
        ),
    ]
