# Generated by Django 4.1.13 on 2024-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_remove_item_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='ID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
